export const PROJECTS = [
  {
    leftSided: false,
    showImage: true,
    private: true,
    header: "LakesAI",
    company: "Vitafluence.ai",
    imgs: [
      "lakesai-overview.png",
      "build-the-future-together-1.png",
      "scientific-tools.png",
    ],
    codeLink: "",
    desc: "LakesAI is an AI-powered life science research platform that brings scientific literature, datasets, collaborative writing, and intelligent research tools into a unified workspace.",
    desc2:
      "I built and contributed to core platform capabilities including a real-time collaborative document editor using Tiptap and Yjs, dataset upload and AI-assisted analysis workflows. I also collaborated on the AI research assistant for drug discovery and repurposing, and took ownership of cloud infrastructure across AWS and GCP, including Docker deployments, ECS, CI/CD, EC2 monitoring, auto-scaling and Nginx configuration.",
    // desc: "LakesAI is an AI-powered life science research platform that brings scientific literature, datasets, collaborative writing, and intelligent research tools into a unified workspace.",
    // desc2:
    //   "I built and contributed to core platform capabilities including a real-time collaborative document editor using Tiptap and Yjs, dataset upload and AI-assisted analysis workflows, and data acquisition pipelines that scraped and processed more than 12,000 assay and compound records from the ReFRAME database. I also implemented end-to-end Stripe subscription billing across backend APIs, webhooks, checkout and frontend workflows, collaborated on the AI research assistant for drug discovery and repurposing, and took ownership of cloud infrastructure across AWS and GCP, including Docker deployments, ECS, CI/CD, EC2 monitoring, auto-scaling and Nginx configuration.",
    technologies: [
      "Python",
      "Django",
      "React",
      "TypeScript",
      "MongoDB",
      "AWS",
      "GCP",
      "Docker",
      "Tiptap",
      "Hocuspocus",
      "Yjs",
      "Selinium",
      "Stripe",
      "GitHub Actions",
      "CI/CD",
      "Celery",
      "Chakra UI",
    ],
    customStyle: {
      background: "#eeeeee",
      border: "0.5px solid #000000",
      btnColor: "#000000",
    },
  },
  {
    leftSided: true,
    showImage: true,
    private: true,
    header: "TutorioGem",
    company: "Vitafluence.ai",
    imgs: ["tutorio-gem.png"],
    codeLink: "",
    desc: "TutorioGem is an AI-powered learning platform designed for universities and life science institutions to centralize educational content and deliver personalized learning experiences.",
    desc2:
      "I built full-stack features across AI-powered learning workflows, including an AI Tutor and RAG-powered research assistant that enables learners to query institutional lectures, slides and research materials using natural language. I also developed personalized learning paths and real-time learning analytics and engagement dashboards, while contributing to the platform's backend APIs, data workflows and cloud deployment infrastructure.",
    // desc: "TutorioGem is an AI-powered learning platform designed for universities and life science institutions to centralize educational content and deliver personalized learning experiences.",
    // desc2:
    //   "I built full-stack features across AI-powered learning workflows, including an AI Tutor and RAG-powered research assistant that enables learners to query institutional lectures, slides and research materials using natural language, as well as automated generation of summaries, quizzes, flashcards and study notes. I also developed personalized learning paths, real-time learning analytics and engagement dashboards, and collaborative faculty workspaces with real-time content editing, while contributing to the platform's backend APIs, data workflows and cloud deployment infrastructure.",
    technologies: [
      "Python",
      "Django",
      "React",
      "TypeScript",
      "MongoDB",
      "RAG",
      "LLMs",
      "AWS",
      "GCP",
      "Docker",
      "Celery",
      "Chakra UI",
    ],
    customStyle: {
      background: "#eeeeee",
      border: "0.5px solid #000000",
      btnColor: "#000000",
    },
  },
  {
    leftSided: false,
    showImage: true,
    private: true,
    header: "Logistics App",
    company: "Personal Project",
    imgs: ["logistics-eq-1.png"],
    projectLink: "https://logistics-ea.netlify.app",
    codeLink: "https://github.com/gdkimaiyo/logistics",
    desc: "Your ideal partner and number one solution for delivering your goods to your clients/customers. This app helps merchants to connect with their customers right on the app.",
    desc2: "I designed this project using Vue3 and Quasar Framework.",
    technologies: [
      "Vue",
      "Quasar Framework",
      "JavaScript",
      "Netlify",
      "HTML",
      "CSS",
    ],
    customStyle: {
      background: "#e9f0f4",
      border: "0.5px solid #1d4778",
      btnColor: "#44AA3C",
    },
  },
  {
    leftSided: true,
    showImage: true,
    private: false,
    header: "Health Facility Locator",
    company: "Personal Project",
    imgs: ["hfl-main.png"],
    codeLink: "https://github.com/gdkimaiyo/hfl",
    desc: "Health Facility Locator. Number one healthcare facility locator in Kenya. Find healthcare facilities near you, their main services, capacity and ownership.",
    desc2:
      "I designed this project with Quasar Framework. Main Concepts I learnt are Component reusability, API integration, MapBox and GeoLocation.",
    technologies: [
      "Vue3",
      "JavaScript",
      "TypeScript",
      "NodeJs",
      "ExpressJS",
      "MongoDB",
      "MapBox",
      "API Integration",
      "HTML",
      "CSS",
    ],
    customStyle: {
      background: "#eeeeee",
      border: "0.5px solid #000000",
      btnColor: "#000000",
    },
  },
  {
    leftSided: false,
    showImage: true,
    private: false,
    header: "Mini-Netflix",
    company: "Personal Project",
    imgs: [
      "mini-netflix-preview-image-1.png",
      "mini-netflix-preview-image-2.png",
    ],
    projectLink: "https://netflix.maiyo.dev",
    codeLink: "https://github.com/gdkimaiyo/netflix",
    desc: "Mini-Netflix is a Netflix clone application. With this app, users can view movie details such as, the movie image, title, overview, year of production, e.t.c. In addition, users can add movies or TV shows they like to their favourites list.",
    technologies: [
      "Angular",
      "JavaScript",
      "NodeJs",
      "ExpressJS",
      "MongoDB",
      "Netlify",
      "Heroku",
      "Docker",
      "API Integration",
      "TMDB API",
      "HTML",
      "CSS",
    ],
    customStyle: {
      background: "#f0e9ee",
      border: "0.5px solid #4b135d",
      btnColor: "#d12e26",
    },
  },
  {
    leftSided: true,
    showImage: true,
    private: true,
    header: "Delivra",
    company: "Personal Project",
    imgs: ["delivra-1.png", "delivra-2.png", "delivra-3.png", "delivra-4.png"],
    codeLink: "https://github.com/gdkimaiyo/delivra",
    desc: "Delivra is a modern delivery platform that connects customers, local merchants and independent riders. Order food and groceries from your favorite businesses and get them delivered fast, while merchants grow their reach and deliverers earn on their own schedule.",
    desc2: "I designed this project using Vue3 and Quasar Framework.",
    technologies: [
      "Vue3",
      "JavaScript",
      "TypeScript",
      "NodeJs",
      "ExpressJS",
      "MongoDB",
      "API Integration",
    ],
    customStyle: {
      background: "rgba(255, 255, 255)",
      border: "0.5px solid #26a69a",
      btnColor: "#007bff",
    },
  },
  {
    leftSided: false,
    showImage: false,
    private: false,
    header: "My Portfolio",
    company: "Personal Project",
    codeLink: "https://github.com/gdkimaiyo/portfolio",
    desc: "This website. A typical portfolio website where one can display information about themselves such as about section, the services they offer, showcase their projects, testimonials and how to get in touch to them.",
    desc2:
      "I designed this project using Vue Js. Code reusability and component reuse were the core concepts I learnt from designing this portfolio website.",
    technologies: ["Vue", "JavaScript", "HTML", "SCSS"],
    customStyle: {
      background: "#e9f0f4",
      border: "0.5px solid #1d4778",
      btnColor: "#007bff",
    },
  },
  // {
  //   leftSided: true,
  //   showImage: true,
  //   private: false,
  //   header: "TaskManager",
  //   imgs: ["task_manager.jpg"],
  //   codeLink: "https://github.com/gdkimaiyo/ci3_app",
  //   desc: "Project management app where users can create and manage a project and its related tasks.",
  //   desc2:
  //     "I designed this project with PHP's CodeIgniter3 Framework. Main Concepts I learnt are CRUD and MySQL.",
  //   technologies: ["PHP", "CodeIgniter 3", "Bootstrap", "HTML", "CSS", "MySQL"],
  //   customStyle: {
  //     background: "#eeeeee",
  //     border: "0.5px solid #000000",
  //     btnColor: "#000000",
  //   },
  // },
  // {
  //   leftSided: false,
  //   showImage: true,
  //   private: false,
  //   header: "ShengBase",
  //   imgs: ["shengbase.png"],
  //   projectLink: "https://shengbase.maiyo.dev",
  //   codeLink: "https://github.com/gdkimaiyo/shengbase",
  //   desc: "ShengBase is a Sheng Dictionary. The dictionary is enriched with latest and old sheng words, which is is constantly updated by users.",
  //   desc2:
  //     "New users can easily create an account and earn points by adding new sheng words or updating existing words in the dictionary.",
  //   technologies: [
  //     "Vue",
  //     "JavaScript",
  //     "NodeJs",
  //     "ExpressJS",
  //     "HTML",
  //     "SCSS",
  //     "MongoDB",
  //   ],
  //   customStyle: {
  //     background: "#edf4e3",
  //     border: "0.5px solid #2e693b",
  //     btnColor: "#006b35",
  //   },
  // },
];

export const SERVICES = [
  {
    title: "Full-Stack Web Development",
    desc: "Building responsive, highly scalable web applications from scratch. I develop interactive frontends using React, Vue or Angular, backed by secure, robust backend architectures using Python (Django) or Laravel.",
    icon: "fas fa-laptop-code",
  },
  {
    title: "API Design & Integration",
    desc: "Designing secure, high-throughput REST APIs, as well as integrating complex third-party services, payment gateways and identity management systems (AWS Cognito, Firebase Auth, JWTs) to keep your data flowing safely.",
    icon: "fas fa-plug",
  },
  {
    title: "Cloud Infrastructure & DevOps",
    desc: "Provisioning and managing cloud environments across AWS, GCP and Azure. I containerize applications with Docker, build automated CI/CD pipelines (GitHub Actions) and configure NGINX/Apache servers for stable, zero-downtime releases.",
    icon: "fas fa-cloud",
  },
  {
    title: "Performance & Database Tuning",
    desc: "Optimizing database schemas (MongoDB, MySQL, PostgreSQL) and implementing caching mechanisms to resolve API latency. I also set up permanent server recovery, automated log-rotation, and auto-scaling to handle sudden traffic spikes gracefully.",
    icon: "fas fa-database",
  },
  {
    title: "Support & Maintenance",
    desc: "Keeping complex web ecosystems up, secure, and running smoothly. I specialize in debugging production outages, upgrading legacy systems and managing custom integrations.",
    icon: "fas fa-tools",
  },
  // {
  //   title: "Coding Tutor",
  //   desc: "I am a Coding Tutor. I teach computer programming languages such as JavaScript, Python, C/C++ and Web Development starting from the basics to advanced concepts. My target age groups are: 7 - 12 years and teenagers",
  //   icon: "fas fa-chalkboard-user",
  // },
];

export const EXPERIENCE = [
  {
    start: "Jul 2023",
    end: "June 2026",
    active: false,
    company: "Vitafluence.ai",
    role: "Senior Full-Stack AI Engineer",
    experience: [
      "Designed, developed and scaled production-grade AI-powered applications for a life-science research platform, combining Python/Django, React, MongoDB, AWS and GCP to support scientific research, education and drug-discovery workflows.",
      "Built RAG-powered Django services and Intelligent Research Assistants that enable researchers and learners to interact with scientific literature, lecture materials and institutional repositories through natural-language queries.",
      "Designed and implemented AI-powered workflows for document generation, summarization, quizzes, flashcards, task management and personalized learning experiences.",
      "Built and maintained React/TypeScript applications powering 50+ specialized scientific analytical tools, including tools for mRNA analysis and drug discovery, as well as research, learning and engage- ment analytics dashboards.",
      "Designed and delivered enterprise EdTech capabilities for life-science, including course management, learner progress tracking and AI-driven personalized study pathways.",
      "Architected and developed a real-time collaborative workspace using Tiptap with Hocuspocus/Yjs, enabling multiple users to edit and collaborate on documents simultaneously.",
      "Designed and maintained backend APIs and microservices using Django, FastAPI, REST APIs and MongoDB, improving performance of data-intensive workflows through aggregation, schema and indexing optimization.",
      "Designed and integrated Stripe subscription and billing infrastructure, covering checkout, payment failures and retries, subscription provisioning, renewals and cancellations through Celery-based asyn- chronous workflows.",
      "Led the design and optimization of GitHub Actions CI/CD pipelines, incorporating automated testing, security scanning and AWS SSM/ECS deployment workflows, reducing manual QA effort by approximately 30% and improving release frequency.",
      "Led application modernization and cloud deployment initiatives by containerizing services with Docker and deploying scalable workloads across AWS ECS and GCP, using Nginx and auto-scaling to support traffic spikes and zero-downtime deployments.",
      "Partnered with engineering, security and QA teams to establish cloud security, deployment and release-management practices, improving environment consistency and production reliability.",
      "Worked closely with product managers, domain scientists and designers to translate complex scientific and business requirements into scalable, production-ready software and AI-powered product capa- bilities.",
    ],
    technologies: [
      "Python",
      "React.js",
      "TypeScript",
      "Django",
      "Node.js",
      "REST APIs",
      "FastAPI",
      "AI",
      "RAG",
      "LLM",
      "AWS",
      "GCP",
      "Docker",
      "CI/CD",
      "Nginx",
      "Apache",
      "Azure",
      "Linux",
      "Celery",
      "Stripe",
    ],
  },
  {
    start: "April 2021",
    end: "June 2023",
    active: false,
    company: "Vitafluence.ai",
    role: "Software Engineer",
    experience: [
      "Developed a secure telehealth platform using Angular, Node.js and MongoDB, delivering REST APIs and responsive interfaces supporting therapist-client workflows and administrative operations.",
      "Designed and implemented an online therapist matching and booking workflow that enabled clients to discover suitable therapists and schedule sessions, streamlining the client-to-therapist placement process.",
      "Developed a therapist onboarding portal allowing healthcare professionals to apply to join the platform, submit required documentation and provide information for administrative review.",
      "Built an administrative dashboard for managing clients, therapists and therapy sessions, including therapist application approval workflows, session monitoring and therapy revenue tracking.",
      "Implemented backend and frontend functionality for role-based workflows, ensuring clients, therapists and administrators could access the appropriate features and operational data.",
      "Integrated AWS Cognito and OIDC authentication to secure user access and protect sensitive client, therapist and therapy-session data.",
      "Developed and maintained RESTful backend services and database workflows using Node.js, Python/Django and MongoDB, supporting core telehealth and administrative functionality.",
      "Contributed to AWS deployments, Dockerized services, CI/CD automation and production troubleshooting, gaining hands-on experience operating production applications and supporting reliable software releases.",
    ],
    technologies: [
      "Angular",
      "TypeScript",
      "Node.js",
      "Express.js",
      "Python",
      "Django",
      "Full-Stack Development",
      "AWS",
      "Docker",
      "CI/CD",
      "MongoDB",
      "REST APIs",
    ],
  },
  {
    start: "Nov 2023",
    end: "Dec 2025",
    active: false,
    company: "EmpathicAI.life, Risch-Rotkreuz, Switzerland",
    role: "Lead Software Engineer",
    experience: [
      "Led development of full-stack product features for a venture-building studio focused on ethical and representative AI solutions for global health.",
      "Designed and developed investor-facing applications using React, Chakra UI, Node.js/Express.js and MongoDB, translating product requirements into scalable production features.",
      "Built secure authentication and onboarding workflows for investor and administrator accounts, in- cluding sign-up, sign-in and referral tracking.",
      "Designed and implemented a role-based Investor Portal enabling investors to securely access, down- load and submit required documentation.",
      "Built automated document-processing workflows that allowed administrators to review, validate, approve or request revisions to investor submissions in real time.",
      "Designed backend APIs for file upload, validation, processing and status tracking, maintaining data integrity throughout the investment onboarding workflow.",
      "Implemented role-based access controls and backend authorization policies to ensure users could access only the resources and workflows appropriate to their roles.",
      "Collaborated with product and business stakeholders to define technical solutions, prioritize features and deliver production-ready full-stack functionality.",
    ],
    technologies: [
      "React.js",
      "Chakra UI",
      "Node.js",
      "AWS",
      "Express.js",
      "REST APIs",
      "MongoDB",
      "RBACs",
    ],
  },
  {
    start: "Jul 2022",
    end: "Feb 2023",
    active: false,
    company: "KARMOD KENYA LTD",
    role: "Software Developer",
    experience: [
      "Developed full stack web platform using Vue.js and Node.js/Express.js to showcase and manage prefabricated building technologies and modular infrastructure solutions.",
      "Developed responsive component driven UI with Vue.js allowing clients across healthcare, construction and education to customise, request and manage prefabricated housing and facility projects.",
      "I built a secure RESTful APIs using Express.js for user registration, login, token validation and user activity logging.",
      "Created multipart file upload endpoints supporting high-resolution image assets and multi-photo galleries for prefabricated model catalogs and site assembly portfolios.",
      "Designed scalable backend endpoints to support real-time cataloging, search, and retrieval of modular building projects and technical specifications.",
    ],
    technologies: ["Vue.js", "Node.js", "MongoDB", "Express.js"],
  },
  {
    start: "March 2019",
    end: "April 2021",
    active: false,
    company: "The Discovery Centre Limited",
    role: "Software Developer",
    experience: [
      "Digitized and developed web-based educational applications for a leading publishing firm in East Africa using Vue, Laravel (PHP) and MySQL.",
      "Translated Figma designs into responsive, cross-device user interfaces, ensuring seamless navigation and accessibility across educational platforms.",
      "Developed gamified learning modules using Vue, integrating interactive quizzes, educational games and immediate feedback loops to enhance student engagement and retention.",
      "Designed and built a student-tracking application in Laravel and MySQL, enabling real-time moni- toring of student progress, activity logs and weekly attendance across multiple regional coding club locations.",
      "Optimized database schemas and query execution in MySQL to maintain low-latency data access for high-concurrency student tracking and reporting systems.",
      "Collaborated developer teams, UI/UX designers and educational content creators to deliver software aligned with KICD curriculum.",
    ],
    technologies: [
      "Vue.js",
      "Laravel",
      "MySQL",
      "PHP",
      "Figma",
      "UI/UX Design",
    ],
  },
  {
    start: "March 2018",
    end: "April 2021",
    active: false,
    company: "The Discovery Centre Limited",
    role: "Coding Instructor",
    experience: [
      "Collaborated with a team of instructors to develop a comprehensive coding curriculum for coding clubs for some popular junior schools in Nairobi, ensuring a structured progression from block-based logic to syntax-heavy languages.",
      "Delivered technical instruction across a broad spectrum of technologies, including Python, JavaScript, and C/C++, Scratch and foundational web development technologies (HTML/CSS).",
      "Developed a custom series of coding challenges to assess student progress and identify areas of improvement.",
      "Mentored students in the fundamentals of computer science, successfully fostering a passion for the field that led several students to pursue advanced studies in Robotics and Computer Science.",
    ],
    technologies: [
      "Tutoring",
      "Python",
      "JavaScript",
      "HTML/CSS",
      "C/C++",
      "Robotics",
      "Web Development",
      "Scratch 3",
    ],
  },
  {
    start: "June 2016",
    end: "March 2017",
    active: false,
    company: "Kapchelal Computer College",
    role: "Training Tutor",
    experience: [
      "Enriched and improved training curriculum for the Training College.",
      "Train students the basics of computer, Internet and World Wide Web (WWW), Microsoft Excel, Microsoft Access, Word and more.",
    ],
    technologies: ["Tutoring", "Basic Computer", "Excel", "Access VBA"],
  },
  {
    start: "May 2015",
    end: "September 2015",
    active: false,
    company: "Ministry of ICT, Department of Information",
    role: "ICT Intern",
    experience: [
      "Repair, maintenance and servicing of computers and Peripherals",
      "Testing and configuring newly acquired and relocated equipment",
      "Simple site creation using PHP, MySQL, HTML, CSS",
      "Network administrations and troubleshooting",
      "Installation of Operating systems, user applications, backing-up of data, digitizing and archiving Historical data.",
      "General Maintenance of computers, among other tasks.",
      "Server configurations, Wi-Fi security testing and CCTV configuration",
    ],
    technologies: [
      "PHP",
      "MySQL",
      "HTML/CSS",
      "Web Development",
      "Network administration",
    ],
  },
];

// export const SERVICES = [
//   {
//     title: "Tailored Web Development",
//     desc: "I design beautiful responsive web applications, which are as easy to use as possible. I build with your goals in mind, whether you want a simple flexible website, a custom web app or a SaaS product.",
//     icon: "fas fa-laptop-code",
//   },
//   {
//     title: "Maintenance and Support",
//     desc: "Carry out mainntence and handle issues arising on your app. Your app is always growing. Whether you are adding new features or making improvements I am here to help. I will always be available to answer any questions you might have.",
//     icon: "fas fa-headset",
//   },
//   {
//     title: "Testing",
//     desc: "I conduct extensive testing using multiple approaches to ensure consistency across broswers, responsiveness, e.t.c to guarantee functionality and everything to work as expected.",
//     icon: "fas fa-vial",
//   },
//   {
//     title: "API Integration",
//     desc: "I offer API integration solutions",
//     icon: "fas fa-gear",
//   },
//   {
//     title: "Cloud and DevOps",
//     desc: "I deploy and manage applications across AWS, Google Cloud, and Azure, including troubleshooting production incidents and setting up CI/CD pipelines and authentication flows (Firebase Auth, AWS Cognito) that keep releases fast, stable, and repeatable.",
//     icon: "fas fa-cloud",
//   },
//   // {
//   //   title: "Coding Tutor",
//   //   desc: "I am a Coding Tutor. I teach computer programming languages such as JavaScript, Python, C/C++ and Web Development starting from the basics to advanced concepts. My target age groups are: 7 - 12 years and teenagers",
//   //   icon: "fas fa-chalkboard-user",
//   // },
// ];

export const SKILLS = [
  {
    category: "AI & LLM Engineering",
    skills: [
      { language: "RAG", icon: "fas fas-gear" },
      { language: "LLM Applications", icon: "fas fas-gear" },
      { language: "Generative AI", icon: "fas fas-gear" },
      { language: "AI Workflows", icon: "fas fas-gear" },
      { language: "Prompt Engineering", icon: "fas fas-gear" },
      { language: "Intelligent Research Assistants", icon: "fas fas-gear" },
      // { language: "Scikit-Learn", icon: "fas fas-gear" },
      // { language: "Claude", icon: "fas fas-gear" },
    ],
  },

  {
    category: "Languages",
    skills: [
      { language: "Python", icon: "fas fas-gear" },
      { language: "TypeScript", icon: "fas fas-gear" },
      { language: "JavaScript (ES6+)", icon: "fas fas-gear" },
      { language: "SQL", icon: "fas fas-gear" },
      // { language: "PHP", icon: "fas fas-gear" },
      // { language: "SQL", icon: "fas fas-gear" },
      // { language: "C/C++", icon: "fas fas-gear" },
    ],
  },

  {
    category: "Full-Stack Development",
    skills: [
      { language: "React.js", icon: "fas fas-gear" },
      { language: "Django", icon: "fas fas-gear" },
      { language: "FastAPI", icon: "fas fas-gear" },
      { language: "Node.js", icon: "fas fas-gear" },
      { language: "Express.js", icon: "fas fas-gear" },
      { language: "REST APIs", icon: "fas fas-gear" },
      { language: "Chakra UI", icon: "fas fas-gear" },
      { language: "Vue.js", icon: "fas fas-gear" },
      { language: "Quasar", icon: "fas fas-gear" },
      { language: "Angular", icon: "fas fas-gear" },
      { language: "Ant Design", icon: "fas fas-gear" },
      // { language: "Laravel", icon: "fas fas-gear" },
      // { language: "WordPress", icon: "fas fas-gear" },
      // { language: "Drupal", icon: "fas fas-gear" },
    ],
  },

  {
    category: "Cloud & DevOps",
    skills: [
      { language: "AWS", icon: "fas fas-gear" },
      { language: "Google Cloud", icon: "fas fas-gear" },
      { language: "Docker", icon: "fas fas-gear" },
      { language: "AWS ECS", icon: "fas fas-gear" },
      { language: "CI/CD", icon: "fas fas-gear" },
      { language: "GitHub Actions", icon: "fas fas-gear" },
      { language: "NGINX", icon: "fas fas-gear" },
      { language: "Linux", icon: "fas fas-gear" },
      // { language: "Azure", icon: "fas fas-gear" },
      // { language: "Apache", icon: "fas fas-gear" },
      // { language: "Netlify", icon: "fas fas-gear" },
      // { language: "Heroku", icon: "fas fas-gear" },
    ],
  },

  {
    category: "Data & Distributed Systems",
    skills: [
      { language: "MongoDB", icon: "fas fas-gear" },
      { language: "PostgreSQL", icon: "fas fas-gear" },
      { language: "Redis", icon: "fas fas-gear" },
      { language: "Celery", icon: "fas fas-gear" },
      { language: "Async Processing", icon: "fas fas-gear" },
      { language: "Database Optimization", icon: "fas fas-gear" },
    ],
  },

  {
    category: "Real-Time Systems & Integrations",
    skills: [
      { language: "Tiptap", icon: "fas fas-gear" },
      { language: "Hocuspocus", icon: "fas fas-gear" },
      { language: "Yjs", icon: "fas fas-gear" },
      { language: "Real-Time Collaboration", icon: "fas fas-gear" },
      { language: "WebSockets", icon: "fas fas-gear" },
      { language: "Stripe", icon: "fas fas-gear" },
      // { language: "Git", icon: "fas fas-gear" },
      // { language: "GitHub", icon: "fas fas-gear" },
      // { language: "Postman", icon: "fas fas-gear" },
      // { language: "Figma", icon: "fas fas-gear" },
    ],
  },
];

// export const SKILLS = [
//   {
//     category: "User Interface",
//     skills: [
//       { language: "HTML", icon: "html5.png" },
//       { language: "CSS", icon: "css.png" },
//       { language: "Bootstrap", icon: "bootstrap.png" },
//       { language: "Tailwind", icon: "tailwindcss.png" },
//     ],
//   },

//   {
//     category: "JavaScript",
//     skills: [
//       { language: "JavaScript", icon: "js.png" },
//       { language: "Vue", icon: "vue.png" },
//       { language: "Angular", icon: "angular.png" },
//       { language: "NodeJs", icon: "nodejs.png" },
//       { language: "ExpressJS", icon: "expressjs.png" },
//     ],
//   },

//   {
//     category: "Python",
//     skills: [
//       { language: "Python", icon: "python.png" },
//       { language: "Flask", icon: "flask.png" },
//       { language: "dJango", icon: "django.png" },
//     ],
//   },

//   {
//     category: "PHP",
//     skills: [
//       { language: "PHP", icon: "php2.png" },
//       { language: "Laravel", icon: "laravel.png" },
//     ],
//   },

//   {
//     category: "Databases",
//     skills: [
//       { language: "MongoBB", icon: "mongodb.png" },
//       { language: "MySQL", icon: "mysql.png" },
//       { language: "PostGreSQL", icon: "postgresql.png" },
//     ],
//   },

//   {
//     category: "Tools & Platforms",
//     skills: [
//       { language: "Git", icon: "git.png" },
//       { language: "GitHub", icon: "github.png" },
//       { language: "AWS", icon: "aws.png" },
//       { language: "Docker", icon: "docker.png" },
//       { language: "Heroku", icon: "heroku.png" },
//       { language: "Netlify", icon: "netlify.png" },
//       // { language: "C", icon: "c.png" },
//     ],
//   },
// ];

export const TESTIMONIALS = [
  {
    name: "Ruth Njeri Mbugua",
    testimony:
      "Over the time I have been with Gideon, I have known him to be a hardworking person who is willing to go an extra mile and beyond to accomplish a task.",
    testimony2:
      "He is a good team player and takes up leadership roles when needed to. He has taken up the role of a project manager which he performed exemplary well. I happily recommend Gideon Kimaiyo to work in any creative organization that values being on top of projects, and is looking for a highly competent, determined and hardworking individual.",
    profession: "Software Engineer, Vitafluence.ai",
    initials: "RN",
  },
];

export const SOCIALS = [
  {
    name: "GitHub",
    logo: "fab fa-square-github",
    color: "rgba(38, 41, 46)",
    link: "https://github.com/gdkimaiyo",
  },
  // {
  //   name: "Medium",
  //   logo: "fab fa-medium",
  //   color: "rgba(0, 0, 0)",
  //   link: "https://medium.com",
  // },
  {
    name: "LinkedIn",
    logo: "fab fa-linkedin",
    color: "rgba(46, 100, 188)",
    link: "https://www.linkedin.com/in/gideon-kimaiyo",
  },
  {
    name: "Twitter",
    logo: "fab fa-square-twitter",
    color: "rgba(74, 153, 233)",
    link: "https://twitter.com/gideonGDK",
  },
  {
    name: "Gmail",
    logo: "fas fa-square-envelope",
    color: "rgba(46, 100, 188)",
    link: "mailto:gdkimaiyo@gmail.com",
  },
];
